=== dkujnisc/seminararbeit-ws17/games.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT games (game*)>
    <!ELEMENT game (gamename, gameconsole, gameyear, gamepublisher, gamemode, gamegenre, eigenebewertung)>
         <!ELEMENT gamename (#PCDATA)>
         <!ELEMENT gameconsole (#PCDATA)>
         <!ELEMENT gameyear (#PCDATA)>
         <!ELEMENT gamepublisher (#PCDATA)>
         <!ELEMENT gamemode (#PCDATA)>
         <!ELEMENT gamegenre (#PCDATA)>
         <!ELEMENT eigenebewertung (#PCDATA)>

=== dkujnisc/seminararbeit-ws17/games.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE games SYSTEM "games.dtd">

<games>
<!-- Games -->
    <!-- GameBoy Games -->
    <game>
        <gamename>Super Mario Land</gamename>
        <gameconsole>Gameboy</gameconsole>
        <gameyear>1989</gameyear>
        <gamepublisher>Nintendo</gamepublisher>
        <gamemode>Einzelspieler</gamemode>
        <gamegenre>Jump 'n' Run</gamegenre>
    </game>
    <game>
        <gamename>The Legend of Zelda: Link's Awakening</gamename>
        <gameconsole>Gameboy</gameconsole>
        <gameyear>1993</gameyear>
        <gamepublisher>Nintendo</gamepublisher>
        <gamemode>Einzelspieler</gamemode>
        <gamegenre>Action-Adventure</gamegenre>
    </game>
    
    <!-- Sega Master System Games -->
    <game>
        <gamename>Alex Kidd in Miracle World</gamename>
        <gameconsole>Sega Master System</gameconsole>
        <gameyear>1986</gameyear>
        <gamepublisher>Sega</gamepublisher>
        <gamemode>Einzelspieler</gamemode>
        <gamegenre>Jump 'n' Run</gamegenre>
    </game>
    <game>
        <gamename>Prince of Persia</gamename>
        <gameconsole>Sega Master System</gameconsole>
        <gameyear>1991</gameyear>
        <gamepublisher>Br√∏derbund</gamepublisher>
        <gamemode>Einzelspieler</gamemode>
        <gamegenre>Jump 'n' Run</gamegenre>
    </game>
    
    <!-- Sega Mega Drive Games -->
    <game>
        <gamename>Sonic the Hedgehog</gamename>
        <gameconsole>Sega Mega Drive</gameconsole>
        <gameyear>1991</gameyear>
        <gamepublisher>Sega</gamepublisher>
        <gamemode>Einzelspieler</gamemode>
        <gamegenre>Jump 'n' Run</gamegenre>
    </game>
    <game>
        <gamename>Cool Spot</gamename>
        <gameconsole>Sega Mega Drive</gameconsole>
        <gameyear>1994</gameyear>
        <gamepublisher>Virgin Interactive</gamepublisher>
        <gamemode>Einzelspieler</gamemode>
        <gamegenre>Jump 'n' Run</gamegenre>
    </game>
    
    <!-- Sony PlayStation 2 Games -->
    <game>
        <gamename>Need for Speed Underground 2</gamename>
        <gameconsole>Sony Playstation 2</gameconsole>
        <gameyear>2004</gameyear>
        <gamepublisher>Electronic Arts</gamepublisher>
        <gamemode>Einzelspieler, Mehrspieler</gamemode>
        <gamegenre>Rennspiel</gamegenre>
    </game>
    <game>
        <gamename>Burnout 3: Takedown</gamename>
        <gameconsole>Sony Playstation 2</gameconsole>
        <gameyear>2004</gameyear>
        <gamepublisher>Electronic Arts</gamepublisher>
        <gamemode>Einzelspieler, Mehrspieler</gamemode>
        <gamegenre>Rennspiel</gamegenre>
    </game>
    
    <!-- Sony PlayStation 4 Games -->
    <game>
        <gamename>The Witcher 3: Wild Hunt</gamename>
        <gameconsole>Sony Playstation 4</gameconsole>
        <gameyear>2015</gameyear>
        <gamepublisher>Namco Bandai Games</gamepublisher>
        <gamemode>Einzelspieler</gamemode>
        <gamegenre>Rollenspiel</gamegenre>
    </game>
    <game>
        <gamename>Horizon Zero Dawn</gamename>
        <gameconsole>Sony Playstation 4</gameconsole>
        <gameyear>2017</gameyear>
        <gamepublisher>Guerilla Games</gamepublisher>
        <gamemode>Einzelspieler</gamemode>
        <gamegenre>Rollenspiel</gamegenre>
    </game>
</games>
